import { initPremiumApp, login, logout } from './modules/auth.js';
import { renderDashboard, refreshDashboard, generateReport, cleanup } from './modules/dashboard.js';
import { renderPackages, exportPackagesData, clearPackageForm, addPackage, filterPackages, deliverPackage, deletePackage } from './modules/packages.js';
import { renderReservations, showReservationCalendar, clearReservationForm, addReservation, filterReservations, deleteReservation } from './modules/reservations.js';
import { renderVisitors, addVisitor, deleteVisitor } from './modules/visitors.js';
import { renderIncidents, addIncident, updateIncidentStatus, deleteIncident } from './modules/incidents.js';
import { renderAdmin, generateSystemReport, showSystemSettings, showUserRegistration, showFinancialPanel, showBackupPanel, showAnalyticsPanel } from './modules/admin.js';
import { renderNotices, addNotice } from './modules/notices.js';
import { renderLostAndFound, addItem } from './modules/lostAndFound.js';
import { markNoticesAsRead, showUserProfile, showSettings, renderNavigation, setActiveNavItem, showAlert } from './modules/ui.js';

document.addEventListener('DOMContentLoaded', function() {
    initPremiumApp();
});

// Expose functions to global scope
window.login = login;
window.logout = logout;
window.renderDashboard = renderDashboard;
window.refreshDashboard = refreshDashboard;
window.generateReport = generateReport;
window.renderPackages = renderPackages;
window.exportPackagesData = exportPackagesData;
window.clearPackageForm = clearPackageForm;
window.addPackage = addPackage;
window.filterPackages = filterPackages;
window.deliverPackage = deliverPackage;
window.deletePackage = deletePackage;
window.renderReservations = renderReservations;
window.showReservationCalendar = showReservationCalendar;
window.clearReservationForm = clearReservationForm;
window.addReservation = addReservation;
window.filterReservations = filterReservations;
window.deleteReservation = deleteReservation;
window.renderVisitors = renderVisitors;
window.addVisitor = addVisitor;
window.deleteVisitor = deleteVisitor;
window.renderIncidents = renderIncidents;
window.addIncident = addIncident;
window.updateIncidentStatus = updateIncidentStatus;
window.deleteIncident = deleteIncident;
window.renderAdmin = renderAdmin;
window.generateSystemReport = generateSystemReport;
window.showSystemSettings = showSystemSettings;
window.showUserRegistration = showUserRegistration;
window.showFinancialPanel = showFinancialPanel;
window.showBackupPanel = showBackupPanel;
window.showAnalyticsPanel = showAnalyticsPanel;
window.renderNotices = renderNotices;
window.addNotice = addNotice;
window.renderLostAndFound = renderLostAndFound;
window.addItem = addItem;
window.markNoticesAsRead = markNoticesAsRead;
window.showUserProfile = showUserProfile;
window.showSettings = showSettings;
window.renderNavigation = renderNavigation;
window.setActiveNavItem = setActiveNavItem;
window.showAlert = showAlert;
window.cleanup = cleanup;